name: CI
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: write
jobs:
  linters:
    uses: ./.github/workflows/lint.yaml
  tests:
    uses: ./.github/workflows/test.yaml
  bench:
    uses: ./.github/workflows/bench.yaml
