name: Test
on: [ workflow_call ]
permissions:
  contents: read
jobs:
  go-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [
            '1.18',
            '1.19',
            '1.20',
            '1.21',
            '1.22',
            '1.23',
            '1.24'
          ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: go test
        run: go test -v -race

  go-fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: go test
        run: go test -run="^$" -fuzz="^Fuzz.*" -fuzztime=1m -v -race
